### ISSUE TITLE
attempt to call a nil value (global 'sortpairs')

### ISSUE THREAD

**Issue by chrisco23** [asdil12/awesome-bluetooth#1]
Is this supposed to work with awesomewm 4.2?  Where is this 'sortpairs' supposed to be?

I get this error message when I click the bluetooth button.

Thanks.

**Comment by ajoboe** [comment]
I got it to work by adding the following to bluetooth.lua
<pre><code>function sortpairs(t, lt)
    local u = { }
    for k, v in pairs(t) do table.insert(u, { key = k, value = v }) end
    table.sort(u, lt)
    return u
end</code></pre>
