### ISSUE TITLE
The unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by freakingeek** [asdil12/awesome-bluetooth#2]
Hi,
I got this error when I try to install it with my AUR helper ...

`The unauthenticated git protocol on port 9418 is no longer supported.`

**Comment by freakingeek** [comment]
@asdil12

**Comment by aylen384** [comment]
I'm not sure what your AUR helper looks like, but you could replace `git://github.com/...` with `https://github.com/...`
